### ISSUE TITLE
Continuous integration and contract testing

### ISSUE THREAD

**Issue by lazywithclass** [bbc/consumer-contracts#16]
This is more of a discussion rather than an issue.

I am interested in understanding how you integrate your contracts in your build pipeline, especially given this sentence from Martin Fowler:

> A failure in an integration contract test shouldn't necessarily break the build in the same way that a normal test failure would.

[source](http://martinfowler.com/bliki/IntegrationContractTest.html)

I honestly don't understand how you can let the build finish with a problem in your infrastructure, it feels like I'm missing something crucial.

I'm currently adding the contracts that I've written using this module in the build pipeline but I'm not sure if they just need to be an extra step like the others or else. Does your experience on the matter hint otherwise?

**Comment by robinjmurphy** [comment]
Hello @lazywithclass. We use this in our build pipeline when we push out a new release, but it can be a good idea to run them on a schedule. It depends on how your API changes.

Personally we run:

```
unit test -> build -> deploy to test -> run contracts -> deploy to live
```

**Comment by lazywithclass** [comment]
Hey @robinjmurphy thanks for the prompt reply. 

I assume your "run contracts" step breaks the build, yes?

Let's say that you have a change in Producer asked by ConsumerA, this change breaks ConsumerB functionality though, at this point do you 

1. break the build for Producer?
2. let it go live and go fix ConsumerB?

I'm not really concerned in the order in which you fix the issue (first the consumer or first the provider), I'm doubtful on how to proceed when the contracts fail.

**Comment by robinjmurphy** [comment]
Yep, we stop the build pipeline and resolve the issue until all contracts are passing.

**Comment by lazywithclass** [comment]
Cool, thanks 👍
