### ISSUE TITLE
Non-HTTP producers

### ISSUE THREAD

**Issue by mkozjak** [bbc/consumer-contracts#28]
Hello,

I've been looking into incorporating Consumer-Driven Contracts into my project microservices which ultimately use [NATS](https://nats.io) at their endpoints.

Is this library supposed to be used only in HTTP API environments or can I use it for other protocols also? I only see you mention HTTP-specific properties...

**Comment by robinjmurphy** [comment]
Hi @mkozjak. The library is very focused on HTTP + JSON producers at present. You're welcome to adapt the code to your needs though if there are bits you can reuse.

**Comment by asko** [comment]
@mkozjak hi, did you found something for NATS?

**Comment by mkozjak** [comment]
@asko: Nope, nothing. Seems like we're ahead of time looking into using these technologies.
I'm yet to find some spare time and implement the messages protocol part on my own...

**Comment by asko** [comment]
@mkozjak thanks! Got the same feeling) Let's see how it goes

**Comment by nspragg** [comment]
Closing issue as it's been inactive for a while. We can reopen if further discussion is required.
